### ISSUE TITLE
GRC file is not running. 

### ISSUE THREAD

**Issue by khalilbd56** [pavel-demin/red-pitaya-notes#918] opened 2019-12-19 17:05 UTC
### Description of the setup:

 * Device: Red pitaya
 * SD card os: Alpine Linux(red pitaya notes)
 * Application: SDR wideband-
 * Other relevant information:

### Description of the problem:
Hello, I did everything as the Pavel demin red pitaya notes directory said. Unfortunately, the grc file is not compiled. It is showing no block name 'red pitaya wide sink/source'.
What should I do now? The red-pitaya has access to the network, the problem seems to the virtual machine. The main network is with WiFi and DHCP enabled.

<img width="687" alt="x" src="https://user-images.githubusercontent.com/59061945/71192261-377c2180-2288-11ea-9d0b-e0adcb97ecf5.PNG">
<img width="434" alt="x4" src="https://user-images.githubusercontent.com/59061945/71192271-3c40d580-2288-11ea-97aa-f43a1e464d0f.PNG">
<img width="488" alt="x2" src="https://user-images.githubusercontent.com/59061945/71192272-3d720280-2288-11ea-846f-bf3ca2645697.PNG">
<img width="518" alt="x5" src="https://user-images.githubusercontent.com/59061945/71192438-92157d80-2288-11ea-8282-13b739a0d3ee.PNG">
<img width="500" alt="x7" src="https://user-images.githubusercontent.com/59061945/71192698-1405a680-2289-11ea-8ac8-14362b5e25d2.PNG">
<img width="496" alt="x8" src="https://user-images.githubusercontent.com/59061945/71192702-1831c400-2289-11ea-81a4-100205632ad3.PNG">
<img width="456" alt="x9" src="https://user-images.githubusercontent.com/59061945/71193910-3b5d7300-228b-11ea-8208-d06e354c639c.PNG">
<img width="487" alt="xx" src="https://user-images.githubusercontent.com/59061945/71195838-06ebb600-228f-11ea-8a9a-f5db55aec956.PNG">
<img width="481" alt="xxx" src="https://user-images.githubusercontent.com/59061945/71201485-6b604280-229a-11ea-8714-febe553cb3ad.PNG">

I have tried as much as I can but still something wrong going on. Different time different types of error.
Thank you.

### Steps to reproduce the problem:

 1.
 2.
 3.

**Comment by pavel-demin** [comment] 2019-12-19 19:17
I think that the main source of the problem is that the `gnuradio` directory is read-only as it's shown on the first screenshot. Could it be a permission problem? When in the `gnuradio` directory, is it possible to create a file with `touch test.txt`?

**Comment by khalilbd56** [comment] 2019-12-19 19:27
Dear Pavel, Thank you for quick feedback.
No, When I am in Gnuradio directory I cannot make a file by a command like touch...' permission denied' is showing.
<img width="636" alt="ddd" src="https://user-images.githubusercontent.com/59061945/71203158-cc3d4a00-229d-11ea-8b30-942c610b0f01.PNG">
What should I do now?

**Comment by pavel-demin** [comment] 2019-12-19 19:42
I don't have enough information to understand why the `gnuradio` directory is read-only on your system. I can only suggest to fix somehow this problem before running `gnuradio-companion`.

**Comment by khalilbd56** [comment] 2019-12-19 19:46
Dear Pavel, 
Can I delete the directory that I cloned in Debian then again clone it? if yes then how? Is this feasible to do so?
Yes, this is kind an uncommon problem, I read through the issue section but nothing matches my situation.

Thank you for your feedback.

**Comment by pavel-demin** [comment] 2019-12-19 20:09
> Can I delete the directory that I cloned in Debian then again clone it? if yes then how? Is this feasible to do so?

Yes. Here are the commands:
```
cd
rm -rf red-pitaya-notes

git clone https://github.com/pavel-demin/red-pitaya-notes
cd red-pitaya-notes/projects/sdr_transceiver_wide/gnuradio

export GRC_BLOCKS_PATH=.
gnuradio-companion trx_wide_template.grc
```

**Comment by khalilbd56** [comment] 2019-12-19 20:13
Dear Pavel,
Unfortunately again deleting permission denied.
<img width="653" alt="hhh" src="https://user-images.githubusercontent.com/59061945/71206261-6902e600-22a4-11ea-8610-441035aa383a.PNG">

Thank you.

**Comment by pavel-demin** [comment] 2019-12-19 21:03
Looks like the problem is that you clone the red-pitaya-notes repository using the root account.

I'd suggest to remove the red-pitya-notes directory using the root account and then clone the repository again using the the red-pitaya account.

I'd also suggest to read some manuals about accounts, permissions and basic commands.

I am closing this issue because the problem isn't with my code but with the way you use the root account.

**Closed by pavel-demin** 2019-12-19 21:03 UTC
